name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            anki-version: "2.1.49"
          - python-version: "3.9"
            anki-version: "2.1.55"
          - python-version: "3.9"
            anki-version: "2.1.66"
          - python-version: "3.9"
            anki-version: "23.12.1"
          - python-version: "3.9"
            anki-version: "25.02"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint -e .[test] anki==${{ matrix.anki-version }}
    - name: Run general unit tests
      run: |
        pytest tests/
